// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(DcapQvlFFI)
    import DcapQvlFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_dcap_qvl_mobile_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_dcap_qvl_mobile_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S: Sequence>(_ writer: inout [UInt8], _ byteArr: S) where S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return try Data(readBytes(&buf, count: Int(len)))
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}

/**
 * Parsed Intel SGX extension fields from a PCK certificate.
 */
public struct PckExtension {
    public var ppid: Data
    public var cpuSvn: Data
    public var pceSvn: UInt16
    public var pceId: Data
    public var fmspc: Data
    public var sgxType: UInt64
    public var platformInstanceId: Data?
    public var rawExtension: Data

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(ppid: Data, cpuSvn: Data, pceSvn: UInt16, pceId: Data, fmspc: Data, sgxType: UInt64, platformInstanceId: Data?, rawExtension: Data) {
        self.ppid = ppid
        self.cpuSvn = cpuSvn
        self.pceSvn = pceSvn
        self.pceId = pceId
        self.fmspc = fmspc
        self.sgxType = sgxType
        self.platformInstanceId = platformInstanceId
        self.rawExtension = rawExtension
    }
}

extension PckExtension: Equatable, Hashable {
    public static func == (lhs: PckExtension, rhs: PckExtension) -> Bool {
        if lhs.ppid != rhs.ppid {
            return false
        }
        if lhs.cpuSvn != rhs.cpuSvn {
            return false
        }
        if lhs.pceSvn != rhs.pceSvn {
            return false
        }
        if lhs.pceId != rhs.pceId {
            return false
        }
        if lhs.fmspc != rhs.fmspc {
            return false
        }
        if lhs.sgxType != rhs.sgxType {
            return false
        }
        if lhs.platformInstanceId != rhs.platformInstanceId {
            return false
        }
        if lhs.rawExtension != rhs.rawExtension {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(ppid)
        hasher.combine(cpuSvn)
        hasher.combine(pceSvn)
        hasher.combine(pceId)
        hasher.combine(fmspc)
        hasher.combine(sgxType)
        hasher.combine(platformInstanceId)
        hasher.combine(rawExtension)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypePckExtension: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PckExtension {
        return
            try PckExtension(
                ppid: FfiConverterData.read(from: &buf),
                cpuSvn: FfiConverterData.read(from: &buf),
                pceSvn: FfiConverterUInt16.read(from: &buf),
                pceId: FfiConverterData.read(from: &buf),
                fmspc: FfiConverterData.read(from: &buf),
                sgxType: FfiConverterUInt64.read(from: &buf),
                platformInstanceId: FfiConverterOptionData.read(from: &buf),
                rawExtension: FfiConverterData.read(from: &buf)
            )
    }

    public static func write(_ value: PckExtension, into buf: inout [UInt8]) {
        FfiConverterData.write(value.ppid, into: &buf)
        FfiConverterData.write(value.cpuSvn, into: &buf)
        FfiConverterUInt16.write(value.pceSvn, into: &buf)
        FfiConverterData.write(value.pceId, into: &buf)
        FfiConverterData.write(value.fmspc, into: &buf)
        FfiConverterUInt64.write(value.sgxType, into: &buf)
        FfiConverterOptionData.write(value.platformInstanceId, into: &buf)
        FfiConverterData.write(value.rawExtension, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePckExtension_lift(_ buf: RustBuffer) throws -> PckExtension {
    return try FfiConverterTypePckExtension.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePckExtension_lower(_ value: PckExtension) -> RustBuffer {
    return FfiConverterTypePckExtension.lower(value)
}

/**
 * Parsed quote with its envelope metadata.
 */
public struct Quote {
    public var header: QuoteHeader
    public var report: Report
    public var certType: UInt16
    /**
     * PCK certificate chain (PEM) when embedded in the quote (cert_type 5).
     */
    public var certChainPem: String?
    /**
     * Hex-encoded FMSPC when extractable from the embedded cert chain.
     */
    public var fmspc: String?
    /**
     * CA identifier ("processor" or "platform") when extractable.
     */
    public var ca: String?
    public var kind: QuoteKind

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(header: QuoteHeader, report: Report, certType: UInt16,
                /* 
                    * PCK certificate chain (PEM) when embedded in the quote (cert_type 5).
                    */ certChainPem: String?,
                /* 
                    * Hex-encoded FMSPC when extractable from the embedded cert chain.
                    */ fmspc: String?,
                /* 
                    * CA identifier ("processor" or "platform") when extractable.
                    */ ca: String?, kind: QuoteKind)
    {
        self.header = header
        self.report = report
        self.certType = certType
        self.certChainPem = certChainPem
        self.fmspc = fmspc
        self.ca = ca
        self.kind = kind
    }
}

extension Quote: Equatable, Hashable {
    public static func == (lhs: Quote, rhs: Quote) -> Bool {
        if lhs.header != rhs.header {
            return false
        }
        if lhs.report != rhs.report {
            return false
        }
        if lhs.certType != rhs.certType {
            return false
        }
        if lhs.certChainPem != rhs.certChainPem {
            return false
        }
        if lhs.fmspc != rhs.fmspc {
            return false
        }
        if lhs.ca != rhs.ca {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(header)
        hasher.combine(report)
        hasher.combine(certType)
        hasher.combine(certChainPem)
        hasher.combine(fmspc)
        hasher.combine(ca)
        hasher.combine(kind)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeQuote: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Quote {
        return
            try Quote(
                header: FfiConverterTypeQuoteHeader.read(from: &buf),
                report: FfiConverterTypeReport.read(from: &buf),
                certType: FfiConverterUInt16.read(from: &buf),
                certChainPem: FfiConverterOptionString.read(from: &buf),
                fmspc: FfiConverterOptionString.read(from: &buf),
                ca: FfiConverterOptionString.read(from: &buf),
                kind: FfiConverterTypeQuoteKind.read(from: &buf)
            )
    }

    public static func write(_ value: Quote, into buf: inout [UInt8]) {
        FfiConverterTypeQuoteHeader.write(value.header, into: &buf)
        FfiConverterTypeReport.write(value.report, into: &buf)
        FfiConverterUInt16.write(value.certType, into: &buf)
        FfiConverterOptionString.write(value.certChainPem, into: &buf)
        FfiConverterOptionString.write(value.fmspc, into: &buf)
        FfiConverterOptionString.write(value.ca, into: &buf)
        FfiConverterTypeQuoteKind.write(value.kind, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeQuote_lift(_ buf: RustBuffer) throws -> Quote {
    return try FfiConverterTypeQuote.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeQuote_lower(_ value: Quote) -> RustBuffer {
    return FfiConverterTypeQuote.lower(value)
}

/**
 * Header section of a quote.
 */
public struct QuoteHeader {
    public var version: UInt16
    public var attestationKeyType: UInt16
    public var teeType: UInt32
    public var qeSvn: UInt16
    public var pceSvn: UInt16
    public var qeVendorId: Data
    public var userData: Data

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(version: UInt16, attestationKeyType: UInt16, teeType: UInt32, qeSvn: UInt16, pceSvn: UInt16, qeVendorId: Data, userData: Data) {
        self.version = version
        self.attestationKeyType = attestationKeyType
        self.teeType = teeType
        self.qeSvn = qeSvn
        self.pceSvn = pceSvn
        self.qeVendorId = qeVendorId
        self.userData = userData
    }
}

extension QuoteHeader: Equatable, Hashable {
    public static func == (lhs: QuoteHeader, rhs: QuoteHeader) -> Bool {
        if lhs.version != rhs.version {
            return false
        }
        if lhs.attestationKeyType != rhs.attestationKeyType {
            return false
        }
        if lhs.teeType != rhs.teeType {
            return false
        }
        if lhs.qeSvn != rhs.qeSvn {
            return false
        }
        if lhs.pceSvn != rhs.pceSvn {
            return false
        }
        if lhs.qeVendorId != rhs.qeVendorId {
            return false
        }
        if lhs.userData != rhs.userData {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(version)
        hasher.combine(attestationKeyType)
        hasher.combine(teeType)
        hasher.combine(qeSvn)
        hasher.combine(pceSvn)
        hasher.combine(qeVendorId)
        hasher.combine(userData)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeQuoteHeader: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> QuoteHeader {
        return
            try QuoteHeader(
                version: FfiConverterUInt16.read(from: &buf),
                attestationKeyType: FfiConverterUInt16.read(from: &buf),
                teeType: FfiConverterUInt32.read(from: &buf),
                qeSvn: FfiConverterUInt16.read(from: &buf),
                pceSvn: FfiConverterUInt16.read(from: &buf),
                qeVendorId: FfiConverterData.read(from: &buf),
                userData: FfiConverterData.read(from: &buf)
            )
    }

    public static func write(_ value: QuoteHeader, into buf: inout [UInt8]) {
        FfiConverterUInt16.write(value.version, into: &buf)
        FfiConverterUInt16.write(value.attestationKeyType, into: &buf)
        FfiConverterUInt32.write(value.teeType, into: &buf)
        FfiConverterUInt16.write(value.qeSvn, into: &buf)
        FfiConverterUInt16.write(value.pceSvn, into: &buf)
        FfiConverterData.write(value.qeVendorId, into: &buf)
        FfiConverterData.write(value.userData, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeQuoteHeader_lift(_ buf: RustBuffer) throws -> QuoteHeader {
    return try FfiConverterTypeQuoteHeader.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeQuoteHeader_lower(_ value: QuoteHeader) -> RustBuffer {
    return FfiConverterTypeQuoteHeader.lower(value)
}

/**
 * SGX enclave report fields.
 */
public struct SgxReport {
    public var cpuSvn: Data
    public var miscSelect: UInt32
    public var attributes: Data
    public var mrEnclave: Data
    public var mrSigner: Data
    public var isvProdId: UInt16
    public var isvSvn: UInt16
    public var reportData: Data

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(cpuSvn: Data, miscSelect: UInt32, attributes: Data, mrEnclave: Data, mrSigner: Data, isvProdId: UInt16, isvSvn: UInt16, reportData: Data) {
        self.cpuSvn = cpuSvn
        self.miscSelect = miscSelect
        self.attributes = attributes
        self.mrEnclave = mrEnclave
        self.mrSigner = mrSigner
        self.isvProdId = isvProdId
        self.isvSvn = isvSvn
        self.reportData = reportData
    }
}

extension SgxReport: Equatable, Hashable {
    public static func == (lhs: SgxReport, rhs: SgxReport) -> Bool {
        if lhs.cpuSvn != rhs.cpuSvn {
            return false
        }
        if lhs.miscSelect != rhs.miscSelect {
            return false
        }
        if lhs.attributes != rhs.attributes {
            return false
        }
        if lhs.mrEnclave != rhs.mrEnclave {
            return false
        }
        if lhs.mrSigner != rhs.mrSigner {
            return false
        }
        if lhs.isvProdId != rhs.isvProdId {
            return false
        }
        if lhs.isvSvn != rhs.isvSvn {
            return false
        }
        if lhs.reportData != rhs.reportData {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(cpuSvn)
        hasher.combine(miscSelect)
        hasher.combine(attributes)
        hasher.combine(mrEnclave)
        hasher.combine(mrSigner)
        hasher.combine(isvProdId)
        hasher.combine(isvSvn)
        hasher.combine(reportData)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSgxReport: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SgxReport {
        return
            try SgxReport(
                cpuSvn: FfiConverterData.read(from: &buf),
                miscSelect: FfiConverterUInt32.read(from: &buf),
                attributes: FfiConverterData.read(from: &buf),
                mrEnclave: FfiConverterData.read(from: &buf),
                mrSigner: FfiConverterData.read(from: &buf),
                isvProdId: FfiConverterUInt16.read(from: &buf),
                isvSvn: FfiConverterUInt16.read(from: &buf),
                reportData: FfiConverterData.read(from: &buf)
            )
    }

    public static func write(_ value: SgxReport, into buf: inout [UInt8]) {
        FfiConverterData.write(value.cpuSvn, into: &buf)
        FfiConverterUInt32.write(value.miscSelect, into: &buf)
        FfiConverterData.write(value.attributes, into: &buf)
        FfiConverterData.write(value.mrEnclave, into: &buf)
        FfiConverterData.write(value.mrSigner, into: &buf)
        FfiConverterUInt16.write(value.isvProdId, into: &buf)
        FfiConverterUInt16.write(value.isvSvn, into: &buf)
        FfiConverterData.write(value.reportData, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSgxReport_lift(_ buf: RustBuffer) throws -> SgxReport {
    return try FfiConverterTypeSgxReport.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSgxReport_lower(_ value: SgxReport) -> RustBuffer {
    return FfiConverterTypeSgxReport.lower(value)
}

/**
 * TCB status paired with the associated advisory IDs.
 */
public struct TcbStatusWithAdvisory {
    public var status: TcbStatus
    public var advisoryIds: [String]

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(status: TcbStatus, advisoryIds: [String]) {
        self.status = status
        self.advisoryIds = advisoryIds
    }
}

extension TcbStatusWithAdvisory: Equatable, Hashable {
    public static func == (lhs: TcbStatusWithAdvisory, rhs: TcbStatusWithAdvisory) -> Bool {
        if lhs.status != rhs.status {
            return false
        }
        if lhs.advisoryIds != rhs.advisoryIds {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(status)
        hasher.combine(advisoryIds)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeTcbStatusWithAdvisory: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TcbStatusWithAdvisory {
        return
            try TcbStatusWithAdvisory(
                status: FfiConverterTypeTcbStatus.read(from: &buf),
                advisoryIds: FfiConverterSequenceString.read(from: &buf)
            )
    }

    public static func write(_ value: TcbStatusWithAdvisory, into buf: inout [UInt8]) {
        FfiConverterTypeTcbStatus.write(value.status, into: &buf)
        FfiConverterSequenceString.write(value.advisoryIds, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTcbStatusWithAdvisory_lift(_ buf: RustBuffer) throws -> TcbStatusWithAdvisory {
    return try FfiConverterTypeTcbStatusWithAdvisory.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTcbStatusWithAdvisory_lower(_ value: TcbStatusWithAdvisory) -> RustBuffer {
    return FfiConverterTypeTcbStatusWithAdvisory.lower(value)
}

/**
 * TDX 1.0 report fields.
 */
public struct Td10Report {
    public var teeTcbSvn: Data
    public var mrSeam: Data
    public var mrSignerSeam: Data
    public var seamAttributes: Data
    public var tdAttributes: Data
    public var xfam: Data
    public var mrTd: Data
    public var mrConfigId: Data
    public var mrOwner: Data
    public var mrOwnerConfig: Data
    public var rtMr0: Data
    public var rtMr1: Data
    public var rtMr2: Data
    public var rtMr3: Data
    public var reportData: Data

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(teeTcbSvn: Data, mrSeam: Data, mrSignerSeam: Data, seamAttributes: Data, tdAttributes: Data, xfam: Data, mrTd: Data, mrConfigId: Data, mrOwner: Data, mrOwnerConfig: Data, rtMr0: Data, rtMr1: Data, rtMr2: Data, rtMr3: Data, reportData: Data) {
        self.teeTcbSvn = teeTcbSvn
        self.mrSeam = mrSeam
        self.mrSignerSeam = mrSignerSeam
        self.seamAttributes = seamAttributes
        self.tdAttributes = tdAttributes
        self.xfam = xfam
        self.mrTd = mrTd
        self.mrConfigId = mrConfigId
        self.mrOwner = mrOwner
        self.mrOwnerConfig = mrOwnerConfig
        self.rtMr0 = rtMr0
        self.rtMr1 = rtMr1
        self.rtMr2 = rtMr2
        self.rtMr3 = rtMr3
        self.reportData = reportData
    }
}

extension Td10Report: Equatable, Hashable {
    public static func == (lhs: Td10Report, rhs: Td10Report) -> Bool {
        if lhs.teeTcbSvn != rhs.teeTcbSvn {
            return false
        }
        if lhs.mrSeam != rhs.mrSeam {
            return false
        }
        if lhs.mrSignerSeam != rhs.mrSignerSeam {
            return false
        }
        if lhs.seamAttributes != rhs.seamAttributes {
            return false
        }
        if lhs.tdAttributes != rhs.tdAttributes {
            return false
        }
        if lhs.xfam != rhs.xfam {
            return false
        }
        if lhs.mrTd != rhs.mrTd {
            return false
        }
        if lhs.mrConfigId != rhs.mrConfigId {
            return false
        }
        if lhs.mrOwner != rhs.mrOwner {
            return false
        }
        if lhs.mrOwnerConfig != rhs.mrOwnerConfig {
            return false
        }
        if lhs.rtMr0 != rhs.rtMr0 {
            return false
        }
        if lhs.rtMr1 != rhs.rtMr1 {
            return false
        }
        if lhs.rtMr2 != rhs.rtMr2 {
            return false
        }
        if lhs.rtMr3 != rhs.rtMr3 {
            return false
        }
        if lhs.reportData != rhs.reportData {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(teeTcbSvn)
        hasher.combine(mrSeam)
        hasher.combine(mrSignerSeam)
        hasher.combine(seamAttributes)
        hasher.combine(tdAttributes)
        hasher.combine(xfam)
        hasher.combine(mrTd)
        hasher.combine(mrConfigId)
        hasher.combine(mrOwner)
        hasher.combine(mrOwnerConfig)
        hasher.combine(rtMr0)
        hasher.combine(rtMr1)
        hasher.combine(rtMr2)
        hasher.combine(rtMr3)
        hasher.combine(reportData)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeTd10Report: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Td10Report {
        return
            try Td10Report(
                teeTcbSvn: FfiConverterData.read(from: &buf),
                mrSeam: FfiConverterData.read(from: &buf),
                mrSignerSeam: FfiConverterData.read(from: &buf),
                seamAttributes: FfiConverterData.read(from: &buf),
                tdAttributes: FfiConverterData.read(from: &buf),
                xfam: FfiConverterData.read(from: &buf),
                mrTd: FfiConverterData.read(from: &buf),
                mrConfigId: FfiConverterData.read(from: &buf),
                mrOwner: FfiConverterData.read(from: &buf),
                mrOwnerConfig: FfiConverterData.read(from: &buf),
                rtMr0: FfiConverterData.read(from: &buf),
                rtMr1: FfiConverterData.read(from: &buf),
                rtMr2: FfiConverterData.read(from: &buf),
                rtMr3: FfiConverterData.read(from: &buf),
                reportData: FfiConverterData.read(from: &buf)
            )
    }

    public static func write(_ value: Td10Report, into buf: inout [UInt8]) {
        FfiConverterData.write(value.teeTcbSvn, into: &buf)
        FfiConverterData.write(value.mrSeam, into: &buf)
        FfiConverterData.write(value.mrSignerSeam, into: &buf)
        FfiConverterData.write(value.seamAttributes, into: &buf)
        FfiConverterData.write(value.tdAttributes, into: &buf)
        FfiConverterData.write(value.xfam, into: &buf)
        FfiConverterData.write(value.mrTd, into: &buf)
        FfiConverterData.write(value.mrConfigId, into: &buf)
        FfiConverterData.write(value.mrOwner, into: &buf)
        FfiConverterData.write(value.mrOwnerConfig, into: &buf)
        FfiConverterData.write(value.rtMr0, into: &buf)
        FfiConverterData.write(value.rtMr1, into: &buf)
        FfiConverterData.write(value.rtMr2, into: &buf)
        FfiConverterData.write(value.rtMr3, into: &buf)
        FfiConverterData.write(value.reportData, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTd10Report_lift(_ buf: RustBuffer) throws -> Td10Report {
    return try FfiConverterTypeTd10Report.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTd10Report_lower(_ value: Td10Report) -> RustBuffer {
    return FfiConverterTypeTd10Report.lower(value)
}

/**
 * TDX 1.5 report fields (extends 1.0).
 */
public struct Td15Report {
    public var base: Td10Report
    public var teeTcbSvn2: Data
    public var mrServiceTd: Data

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(base: Td10Report, teeTcbSvn2: Data, mrServiceTd: Data) {
        self.base = base
        self.teeTcbSvn2 = teeTcbSvn2
        self.mrServiceTd = mrServiceTd
    }
}

extension Td15Report: Equatable, Hashable {
    public static func == (lhs: Td15Report, rhs: Td15Report) -> Bool {
        if lhs.base != rhs.base {
            return false
        }
        if lhs.teeTcbSvn2 != rhs.teeTcbSvn2 {
            return false
        }
        if lhs.mrServiceTd != rhs.mrServiceTd {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(base)
        hasher.combine(teeTcbSvn2)
        hasher.combine(mrServiceTd)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeTd15Report: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Td15Report {
        return
            try Td15Report(
                base: FfiConverterTypeTd10Report.read(from: &buf),
                teeTcbSvn2: FfiConverterData.read(from: &buf),
                mrServiceTd: FfiConverterData.read(from: &buf)
            )
    }

    public static func write(_ value: Td15Report, into buf: inout [UInt8]) {
        FfiConverterTypeTd10Report.write(value.base, into: &buf)
        FfiConverterData.write(value.teeTcbSvn2, into: &buf)
        FfiConverterData.write(value.mrServiceTd, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTd15Report_lift(_ buf: RustBuffer) throws -> Td15Report {
    return try FfiConverterTypeTd15Report.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTd15Report_lower(_ value: Td15Report) -> RustBuffer {
    return FfiConverterTypeTd15Report.lower(value)
}

/**
 * Verified-quote result.
 */
public struct VerifiedReport {
    public var status: String
    public var advisoryIds: [String]
    public var report: Report
    public var ppid: Data
    public var qeStatus: TcbStatusWithAdvisory
    public var platformStatus: TcbStatusWithAdvisory

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(status: String, advisoryIds: [String], report: Report, ppid: Data, qeStatus: TcbStatusWithAdvisory, platformStatus: TcbStatusWithAdvisory) {
        self.status = status
        self.advisoryIds = advisoryIds
        self.report = report
        self.ppid = ppid
        self.qeStatus = qeStatus
        self.platformStatus = platformStatus
    }
}

extension VerifiedReport: Equatable, Hashable {
    public static func == (lhs: VerifiedReport, rhs: VerifiedReport) -> Bool {
        if lhs.status != rhs.status {
            return false
        }
        if lhs.advisoryIds != rhs.advisoryIds {
            return false
        }
        if lhs.report != rhs.report {
            return false
        }
        if lhs.ppid != rhs.ppid {
            return false
        }
        if lhs.qeStatus != rhs.qeStatus {
            return false
        }
        if lhs.platformStatus != rhs.platformStatus {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(status)
        hasher.combine(advisoryIds)
        hasher.combine(report)
        hasher.combine(ppid)
        hasher.combine(qeStatus)
        hasher.combine(platformStatus)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeVerifiedReport: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VerifiedReport {
        return
            try VerifiedReport(
                status: FfiConverterString.read(from: &buf),
                advisoryIds: FfiConverterSequenceString.read(from: &buf),
                report: FfiConverterTypeReport.read(from: &buf),
                ppid: FfiConverterData.read(from: &buf),
                qeStatus: FfiConverterTypeTcbStatusWithAdvisory.read(from: &buf),
                platformStatus: FfiConverterTypeTcbStatusWithAdvisory.read(from: &buf)
            )
    }

    public static func write(_ value: VerifiedReport, into buf: inout [UInt8]) {
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterSequenceString.write(value.advisoryIds, into: &buf)
        FfiConverterTypeReport.write(value.report, into: &buf)
        FfiConverterData.write(value.ppid, into: &buf)
        FfiConverterTypeTcbStatusWithAdvisory.write(value.qeStatus, into: &buf)
        FfiConverterTypeTcbStatusWithAdvisory.write(value.platformStatus, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeVerifiedReport_lift(_ buf: RustBuffer) throws -> VerifiedReport {
    return try FfiConverterTypeVerifiedReport.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeVerifiedReport_lower(_ value: VerifiedReport) -> RustBuffer {
    return FfiConverterTypeVerifiedReport.lower(value)
}

/**
 * Error type returned by every public binding function.
 *
 * The variants distinguish the broad failure category so callers can branch
 * on them in Kotlin/Swift; the inner message preserves the full anyhow chain
 * for human-readable diagnostics.
 */
public enum DcapError {
    /**
     * The quote, collateral, or PEM input could not be parsed.
     */
    case Parse(message: String)

    /**
     * Verification failed (signature, certificate chain, TCB, or QE identity).
     */
    case Verify(message: String)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDcapError: FfiConverterRustBuffer {
    typealias SwiftType = DcapError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DcapError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .Parse(
                message: FfiConverterString.read(from: &buf)
            )

        case 2: return try .Verify(
                message: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DcapError, into buf: inout [UInt8]) {
        switch value {
        case .Parse(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(1))
        case .Verify(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(2))
        }
    }
}

extension DcapError: Equatable, Hashable {}

extension DcapError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * SGX or TDX quote type tag.
 */

public enum QuoteKind {
    case sgx
    case tdx
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeQuoteKind: FfiConverterRustBuffer {
    typealias SwiftType = QuoteKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> QuoteKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .sgx

        case 2: return .tdx

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: QuoteKind, into buf: inout [UInt8]) {
        switch value {
        case .sgx:
            writeInt(&buf, Int32(1))

        case .tdx:
            writeInt(&buf, Int32(2))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeQuoteKind_lift(_ buf: RustBuffer) throws -> QuoteKind {
    return try FfiConverterTypeQuoteKind.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeQuoteKind_lower(_ value: QuoteKind) -> RustBuffer {
    return FfiConverterTypeQuoteKind.lower(value)
}

extension QuoteKind: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * Tagged-union report: one of SGX, TDX 1.0, or TDX 1.5.
 */

public enum Report {
    case sgx(report: SgxReport)
    case td10(report: Td10Report)
    case td15(report: Td15Report)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeReport: FfiConverterRustBuffer {
    typealias SwiftType = Report

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Report {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .sgx(report: FfiConverterTypeSgxReport.read(from: &buf))

        case 2: return try .td10(report: FfiConverterTypeTd10Report.read(from: &buf))

        case 3: return try .td15(report: FfiConverterTypeTd15Report.read(from: &buf))

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Report, into buf: inout [UInt8]) {
        switch value {
        case let .sgx(report):
            writeInt(&buf, Int32(1))
            FfiConverterTypeSgxReport.write(report, into: &buf)

        case let .td10(report):
            writeInt(&buf, Int32(2))
            FfiConverterTypeTd10Report.write(report, into: &buf)

        case let .td15(report):
            writeInt(&buf, Int32(3))
            FfiConverterTypeTd15Report.write(report, into: &buf)
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeReport_lift(_ buf: RustBuffer) throws -> Report {
    return try FfiConverterTypeReport.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeReport_lower(_ value: Report) -> RustBuffer {
    return FfiConverterTypeReport.lower(value)
}

extension Report: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * Mirror of `dcap_qvl::tcb_info::TcbStatus`.
 */

public enum TcbStatus {
    case upToDate
    case outOfDateConfigurationNeeded
    case outOfDate
    case configurationAndSwHardeningNeeded
    case configurationNeeded
    case swHardeningNeeded
    case revoked
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeTcbStatus: FfiConverterRustBuffer {
    typealias SwiftType = TcbStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TcbStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .upToDate

        case 2: return .outOfDateConfigurationNeeded

        case 3: return .outOfDate

        case 4: return .configurationAndSwHardeningNeeded

        case 5: return .configurationNeeded

        case 6: return .swHardeningNeeded

        case 7: return .revoked

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TcbStatus, into buf: inout [UInt8]) {
        switch value {
        case .upToDate:
            writeInt(&buf, Int32(1))

        case .outOfDateConfigurationNeeded:
            writeInt(&buf, Int32(2))

        case .outOfDate:
            writeInt(&buf, Int32(3))

        case .configurationAndSwHardeningNeeded:
            writeInt(&buf, Int32(4))

        case .configurationNeeded:
            writeInt(&buf, Int32(5))

        case .swHardeningNeeded:
            writeInt(&buf, Int32(6))

        case .revoked:
            writeInt(&buf, Int32(7))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTcbStatus_lift(_ buf: RustBuffer) throws -> TcbStatus {
    return try FfiConverterTypeTcbStatus.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTcbStatus_lower(_ value: TcbStatus) -> RustBuffer {
    return FfiConverterTypeTcbStatus.lower(value)
}

extension TcbStatus: Equatable, Hashable {}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

/**
 * Parse the Intel SGX extension from a PEM-encoded PCK certificate chain.
 */
public func parsePckExtensionFromPem(pem: Data) throws -> PckExtension {
    return try FfiConverterTypePckExtension.lift(rustCallWithError(FfiConverterTypeDcapError.lift) {
        uniffi_dcap_qvl_mobile_fn_func_parse_pck_extension_from_pem(
            FfiConverterData.lower(pem), $0
        )
    })
}

/**
 * Parse an SGX/TDX quote binary into a structured [`Quote`].
 */
public func parseQuote(rawQuote: Data) throws -> Quote {
    return try FfiConverterTypeQuote.lift(rustCallWithError(FfiConverterTypeDcapError.lift) {
        uniffi_dcap_qvl_mobile_fn_func_parse_quote(
            FfiConverterData.lower(rawQuote), $0
        )
    })
}

/**
 * Verify a quote against PCCS collateral JSON, using Intel's production
 * root CA and the `ring` crypto backend.
 *
 * `collateral_json` is the raw response body returned by a PCCS — the same
 * shape produced by `dcap_qvl::collateral::CollateralClient`.
 */
public func verify(rawQuote: Data, collateralJson: Data, nowSecs: UInt64) throws -> VerifiedReport {
    return try FfiConverterTypeVerifiedReport.lift(rustCallWithError(FfiConverterTypeDcapError.lift) {
        uniffi_dcap_qvl_mobile_fn_func_verify(
            FfiConverterData.lower(rawQuote),
            FfiConverterData.lower(collateralJson),
            FfiConverterUInt64.lower(nowSecs), $0
        )
    })
}

/**
 * Verify a quote against PCCS collateral JSON, with a custom DER-encoded
 * root CA.
 */
public func verifyWithRootCa(rawQuote: Data, collateralJson: Data, rootCaDer: Data, nowSecs: UInt64) throws -> VerifiedReport {
    return try FfiConverterTypeVerifiedReport.lift(rustCallWithError(FfiConverterTypeDcapError.lift) {
        uniffi_dcap_qvl_mobile_fn_func_verify_with_root_ca(
            FfiConverterData.lower(rawQuote),
            FfiConverterData.lower(collateralJson),
            FfiConverterData.lower(rootCaDer),
            FfiConverterUInt64.lower(nowSecs), $0
        )
    })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_dcap_qvl_mobile_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_dcap_qvl_mobile_checksum_func_parse_pck_extension_from_pem() != 33361 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_dcap_qvl_mobile_checksum_func_parse_quote() != 37454 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_dcap_qvl_mobile_checksum_func_verify() != 34688 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_dcap_qvl_mobile_checksum_func_verify_with_root_ca() != 29462 {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
